server:
  port: 800
db:
  type: sqlite
  sqlite3:
    path: /var/db/backend-blog/my-blog
log:
  name: middleware
  path: /var/log/go/backend-blog
  # 单位：MB
  maxSize: 10
file:
  path:
    # 系统路径
    system: /home
    # 资源路径
    resource: /file/public
exifTool:
  path: /usr/bin/backend-blog/Image-ExifTool-12.96